name: DigiMess
description: An app to help organizations manage their food mess, mainly colleges. University Android mini project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Bloc for architecture
  flutter_bloc: ^6.1.3
  # Class equability
  equatable: ^1.1.1
  # To check network connection
  connectivity: ^3.0.2
  # Networking
  http: ^0.13.0
  # Shared preferences
  shared_preferences: ^2.0.4
  # For proper keyboard scrolling
  keyboard_avoider: ^0.1.2
  # Svg icons rendering
  flutter_svg: ^0.19.3
  # Non dismissible async spinner
  modal_progress_hud: ^0.1.3
  # Date library
  intl: ^0.17.0
  # Page animations
  page_transition: ^1.1.7+6
  # Firebase dependencies
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  # crypto functions
  crypto: ^3.0.0
  # charts library
  fl_chart: ^0.12.3
  # work manager for notification services
  #workmanager: ^0.2.3
  # notification library
  flutter_local_notifications: ^4.0.1+2
  # share intent library
  share: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/ic_foreground.svg
    - assets/logo/ic_launcher_default.svg
    - assets/logo/ic_launcher_round.svg
    - assets/logo/ic_launcher_playstore.png
    - assets/logo/ic_foreground.png
    - assets/logo/ic_background.png
    - assets/icons/no_internet_icon.svg
    - assets/background/top_left_bg.svg
    - assets/background/bottom_right_bg.svg
    - assets/icons/home.svg
    - assets/icons/about.svg
    - assets/icons/complaints.svg
    - assets/icons/help.svg
    - assets/icons/leaves.svg
    - assets/icons/menu.svg
    - assets/icons/notices.svg
    - assets/icons/payments.svg
    - assets/icons/profile.svg
    - assets/icons/settings.svg
    - assets/icons/share.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Comfortaa
     fonts:
       - asset: assets/fonts/Comfortaa-Bold.ttf
       - asset: assets/fonts/Comfortaa-Light.ttf
       - asset: assets/fonts/Comfortaa-Medium.ttf
       - asset: assets/fonts/Comfortaa-Regular.ttf
       - asset: assets/fonts/Comfortaa-SemiBold.ttf
       - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
