name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter analyze --no-fatal-warnings --no-fatal-infos

      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      - run: |
          wget https://gist.githubusercontent.com/Sharkaboi/dc9935bf1485ac361494425556a7d582/raw/2c32001133d97bfadaf0d8abc3d5f3b45bc4a5a3/script
          chmod +x script
          ./script source_code
